#!/usr/bin/env python3
# Jacob Ursenbach
# CPSC 386-01
# 2022-07-21
# jlursenbach@csu.fullerton.edu
# @jlursenbach
#
# Lab 02-00
#
# Blackjack game
#


--- Header FRAME------------------------------------------------
 ---  BUY IN  ---
--- DOUBLE DOWN!!! ---
  ---  HIT?  ---
--- Table FRAME-------------------------------------------------
                   v TURN v
Cash:               10,000      10,000,000   10,000      10,000
Score:  21          21          BUST         LOOSER      WINNER
        Dealer      Jacob       Debra        John        Bishop
        |A ♣|       |9 ♥|       |A ♣|        |Q ♣|       |A ♣|
        |BBB|       |A ♣|       |5 ♣|        |A ♣|       |10♣|
                    |K ♣|       |A ♣|
                                |A ♣|
                                |A ♣|
--- INTERFACE FRAME --------------------------------------------
JACOB'S TURN:       | < NAME FRAME
-> 21 points <-     | < RESULTS FRAME
   _______          -----------
  |9|A|K ♠|         | < CARD FRAME
  |♥|♣|♠_K|        
1 - Hit             | < QUERY FRAME
2 - Stand
